### ISSUE TITLE
Missing player stats

### ISSUE THREAD

**Issue by VirtualLobster** [fraxiinus/roflxd.cs#4]
Hello. I encountered two .rofl files from the same user. Both files was parsed without error, but PlayerStatistics property was an empty array in both results of RoflReader.LoadAsync(). Which means I have some data like match duration, but no player data. Is this a known issue and do you know the cause?

**Comment by fraxiinus** [comment]
Hi, it appears that in patch 13,20, Riot has stopped populating the required 'statsJson' field. Any replays downloaded for that patch will not have any player data associated with it. Unfortunately I don't know if this is a decision Riot has deliberately made, or if it is just a bug.

**Comment by fraxiinus** [comment]
Reference to issue on Riot developer relations repository:
https://github.com/RiotGames/developer-relations/issues/831

**Comment by fraxiinus** [comment]
As of patch 13.22, this issue has been fixed by Riot
