### ISSUE TITLE
No support for current replay files

### ISSUE THREAD

**Issue by VirtualLobster** [fraxiinus/roflxd.cs#6]
Hi, it seems that new replay format is not supported. I get error "System.Exception: 'file signature does not match ROFL format'". This started to happen 5th of May 2024. Let me know if you need sample rofl-file or anything else! 

Thank you for a great job with this project! 

Kind regards

**Comment by fraxiinus** [comment]
known issue with new files, they contain no data: https://github.com/fraxiinus/ReplayBook/issues/299

**Comment by fraxiinus** [comment]
roflxd.cs has been updated to version 3.0.0 which now supports both rofl (pre 14.9) and rofl2 (post 14.11) files.
